### ISSUE TITLE
NPE in Omero opener

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/bigdataviewer-image-loaders#2]
With the image https://omero.epfl.ch/webclient/img_detail/230498/

```
	at ch.epfl.biop.bdv.img.omero.OmeroBdvOpener.create(OmeroBdvOpener.java:390)
	at ch.epfl.biop.bdv.img.omero.command.OpenWithBigDataViewerOmeroBridgeCommand.run(OpenWithBigDataViewerOmeroBridgeCommand.java:106)
```

**Comment by NicoKiaru** [comment]
It's a metadata / unit problem.

```
			if (!planeinfo.getPositionX().getUnit().equals(
```

**Comment by NicoKiaru** [comment]
Already fixed, I lost track of the commit
