### ISSUE TITLE
Can't open LIF files anymore

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/bigdataviewer-image-loaders#3]
I need to investigate and make a minimal example.

I get this error:

```
java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:740)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:718)
	at loci.common.NIOByteBufferProvider.allocateDirect(NIOByteBufferProvider.java:127)
	at loci.common.NIOByteBufferProvider.allocate(NIOByteBufferProvider.java:112)
	at loci.common.NIOFileHandle.buffer(NIOFileHandle.java:647)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:133)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:151)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:165)
	at loci.common.Location.getHandle(Location.java:522)
	at loci.common.Location.getHandle(Location.java:462)
	at loci.common.Location.getHandle(Location.java:443)
	at loci.common.Location.getHandle(Location.java:426)
	at loci.common.Location.checkValidId(Location.java:551)
	at loci.formats.ImageReader.getReader(ImageReader.java:182)
	at loci.formats.ImageReader.setId(ImageReader.java:844)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.ChannelSeparator.setId(ChannelSeparator.java:293)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.Memoizer.setId(Memoizer.java:690)
	at ch.epfl.biop.bdv.img.legacy.bioformats.BioFormatsBdvOpener.getNewReader(BioFormatsBdvOpener.java:456)
	at ch.epfl.biop.bdv.img.legacy.bioformats.ReaderPool.createObject(ReaderPool.java:48)
	at ch.epfl.biop.bdv.img.legacy.bioformats.ReaderPool.createObject(ReaderPool.java:33)
	at ch.epfl.biop.bdv.img.ResourcePool.acquire(ResourcePool.java:77)
	at ch.epfl.biop.bdv.img.legacy.bioformats.BioFormatsArrayLoaders$BioFormatsUnsignedByteArrayLoader.loadArray(BioFormatsArrayLoaders.java:75)
	at ch.epfl.biop.bdv.img.legacy.bioformats.BioFormatsArrayLoaders$BioFormatsUnsignedByteArrayLoader.loadArray(BioFormatsArrayLoaders.java:60)
	at bdv.img.cache.VolatileGlobalCellCache.lambda$createImg$0(VolatileGlobalCellCache.java:195)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.lambda$get$0(LoaderCacheKeyAdapter.java:55)
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:135)
	at net.imglib2.cache.util.LoaderCacheKeyAdapter.get(LoaderCacheKeyAdapter.java:53)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:484)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:53)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:531)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:508)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:181)
```

Most probably related to https://github.com/BIOP/ijp-kheops/issues/16

AAARRGH!!

**Comment by NicoKiaru** [comment]
Fixed in https://github.com/BIOP/bigdataviewer-image-loaders/commit/cb5f0d961bba7bf01e9857775b50332e2446fdc0
